listener:
  discord_token: YOUR_DISCORD_TOKEN
  channel_ids:
    - 'CHANNEL_ID_1'
    - 'CHANNEL_ID_2'
  reconnect_attempts: 3
  message_throttle: 100

parser:
  formats:
    - standard

risk:
  max_position_size: 0.02  # 2% of account
  max_loss_per_trade: 0.01  # 1% of account
  daily_loss_limit: 0.05  # 5% of account
  max_open_positions: 5
  correlation_threshold: 0.7

broker:
  broker_type: mock  # 'mock', 'ibkr', etc.
  trading_mode: paper  # 'paper' or 'live'
  credentials:
    api_key: ''
    api_secret: ''
  api_endpoints:
    base_url: ''
    order_endpoint: '/api/orders'
  connection_timeout: 30

logging:
  level: INFO
  file: quant_bot.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s' 